# Generated by Django 3.2.9 on 2021-11-26 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio_Product',
            new_name='PortfolioProduct',
        ),
        migrations.RenameModel(
            old_name='Portfolio_Showcase',
            new_name='PortfolioShowcase',
        ),
    ]
