# Generated by Django 3.2.9 on 2021-11-26 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20211126_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioproduct',
            options={},
        ),
        migrations.AlterModelOptions(
            name='portfolioshowcase',
            options={},
        ),
        migrations.AlterModelOptions(
            name='proposal',
            options={},
        ),
        migrations.RenameField(
            model_name='proposal',
            old_name='request',
            new_name='proposalText',
        ),
    ]
