# Generated by Django 4.0.2 on 2022-03-01 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_services_alter_portfolioproduct_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioproduct',
            old_name='aboutProduct',
            new_name='about',
        ),
        migrations.RemoveField(
            model_name='portfolioproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='portfolioproduct',
            name='link',
        ),
        migrations.AddField(
            model_name='portfolioproduct',
            name='portfolio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='services.portfolioshowcase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolioproduct',
            name='technology',
            field=models.CharField(default=12121, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SubServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='services.services')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='services.portfolioproduct')),
                ('portfolio_showcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='services.portfolioshowcase')),
            ],
        ),
    ]
