# Generated by Django 3.2.8 on 2021-10-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Growth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp', models.IntegerField(verbose_name='Years of Experience')),
                ('cilents', models.IntegerField(verbose_name='Global Happy Clients')),
                ('projects', models.IntegerField(verbose_name='Completed Projects')),
                ('working', models.IntegerField(verbose_name='Working Hours')),
                ('ratting', models.IntegerField(verbose_name='Costumer Rating')),
            ],
            options={
                'verbose_name': 'Company Growth',
                'verbose_name_plural': 'Company Growth',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='Our_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('picture', models.ImageField(upload_to='our-team', verbose_name='Image')),
                ('post', models.CharField(max_length=255, verbose_name='Post in Company')),
                ('intro', models.TextField(verbose_name='A Little Introduction')),
            ],
            options={
                'verbose_name': 'Our Team',
                'verbose_name_plural': 'Our Team',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('picture', models.ImageField(upload_to='our-products', verbose_name='Product Icon')),
                ('link', models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='Hyperlink to product')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=255, verbose_name='Customer`s Name')),
                ('review', models.TextField(verbose_name='Customer`s Review')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
