# Generated by Django 3.2.8 on 2021-10-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_growth',
            name='days',
            field=models.IntegerField(default=1, verbose_name='Working Days a week'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company_growth',
            name='ratting',
            field=models.FloatField(verbose_name='Costumer Rating'),
        ),
    ]
