# Generated by Django 3.2.8 on 2021-10-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211027_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyGrowth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField(verbose_name='Years of Experience')),
                ('cilents', models.IntegerField(verbose_name='Global Happy Clients')),
                ('projects', models.IntegerField(verbose_name='Completed Projects')),
                ('working', models.IntegerField(verbose_name='Working Hours')),
                ('days', models.IntegerField(verbose_name='Working Days a week')),
                ('ratting', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Costumer Rating')),
            ],
            options={
                'verbose_name': 'Company Growth',
                'verbose_name_plural': 'Company Growth',
            },
        ),
        migrations.RenameModel(
            old_name='Our_Team',
            new_name='OurTeam',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.DeleteModel(
            name='Company_Growth',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='home_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
