# Generated by Django 3.2.8 on 2021-10-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211028_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companygrowth',
            options={},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={},
        ),
        migrations.AddField(
            model_name='contact',
            name='is_contacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='companygrowth',
            name='ratting',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Costumer Rating'),
        ),
    ]
