# Generated by Django 3.2.8 on 2021-10-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211028_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companygrowth',
            name='ratting',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Custumer Rating'),
        ),
    ]
