# Generated by Django 3.2.9 on 2021-11-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=255, verbose_name='Lastt Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone Number')),
                ('course', models.CharField(max_length=255, verbose_name='Course Name')),
            ],
            options={
                'verbose_name': 'Course Form',
                'verbose_name_plural': 'Course Forms',
            },
        ),
        migrations.CreateModel(
            name='InternshipForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=255, verbose_name='Lastt Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone Number')),
                ('cv', models.FileField(upload_to='intership-form', verbose_name='CV')),
            ],
            options={
                'verbose_name': 'Internship Form',
                'verbose_name_plural': 'Internship Forms',
            },
        ),
    ]
